"""
Prompts package for DeepCode AI agents.

This package contains various prompt templates used by different AI agents
in the DeepCode system for research analysis and code implementation.
"""

from .code_prompts import (
    PAPER_INPUT_ANALYZER_PROMPT,
    PAPER_DOWNLOADER_PROMPT,
    PAPER_REFERENCE_ANALYZER_PROMPT,
    GITHUB_DOWNLOAD_PROMPT,
    PAPER_ALGORITHM_ANALYSIS_PROMPT,
    PAPER_CONCEPT_ANALYSIS_PROMPT,
    CODE_PLANNING_PROMPT,
    STRUCTURE_GENERATOR_PROMPT,
    CODE_IMPLEMENTATION_PROMPT,
    CONVERSATION_SUMMARY_PROMPT,
    SLIDING_WINDOW_SYSTEM_PROMPT,
    PURE_CODE_IMPLEMENTATION_SYSTEM_PROMPT,
    PURE_CODE_IMPLEMENTATION_SYSTEM_PROMPT_INDEX,
    GENERAL_CODE_IMPLEMENTATION_SYSTEM_PROMPT,
    CHAT_AGENT_PLANNING_PROMPT,
    PAPER_ALGORITHM_ANALYSIS_PROMPT_TRADITIONAL,
    PAPER_CONCEPT_ANALYSIS_PROMPT_TRADITIONAL,
    CODE_PLANNING_PROMPT_TRADITIONAL,
)

__all__ = [
    "PAPER_INPUT_ANALYZER_PROMPT",
    "PAPER_DOWNLOADER_PROMPT",
    "PAPER_REFERENCE_ANALYZER_PROMPT",
    "GITHUB_DOWNLOAD_PROMPT",
    "PAPER_ALGORITHM_ANALYSIS_PROMPT",
    "PAPER_CONCEPT_ANALYSIS_PROMPT",
    "CODE_PLANNING_PROMPT",
    "STRUCTURE_GENERATOR_PROMPT",
    "CODE_IMPLEMENTATION_PROMPT",
    "CONVERSATION_SUMMARY_PROMPT",
    "SLIDING_WINDOW_SYSTEM_PROMPT",
    "PURE_CODE_IMPLEMENTATION_SYSTEM_PROMPT",
    "PURE_CODE_IMPLEMENTATION_SYSTEM_PROMPT_INDEX",
    "GENERAL_CODE_IMPLEMENTATION_SYSTEM_PROMPT",
    "CHAT_AGENT_PLANNING_PROMPT",
    "PAPER_ALGORITHM_ANALYSIS_PROMPT_TRADITIONAL",
    "PAPER_CONCEPT_ANALYSIS_PROMPT_TRADITIONAL",
    "CODE_PLANNING_PROMPT_TRADITIONAL",
]
